name: fieldshub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies: 
  flutter:
    sdk: flutter

  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.0
  firebase_database: ^11.0.3
  firebase_auth: ^5.1.0
  mailer: ^6.0.1
  fl_chart: ^0.70.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0  
  http: ^1.2.1
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  firebase_storage: ^12.3.2
  flutter_rating_bar: ^4.0.1
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true