// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf24iLI8u6sWdyJMNw-Q5_ueJo6Jl38fU',
    appId: '1:442693512571:web:521cf73c2d61bea12da1de',
    messagingSenderId: '442693512571',
    projectId: 'sportfields-ff16a',
    authDomain: 'sportfields-ff16a.firebaseapp.com',
    databaseURL: 'https://sportfields-ff16a-default-rtdb.firebaseio.com',
    storageBucket: 'sportfields-ff16a.firebasestorage.app',
    measurementId: 'G-1C8J8VTLGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIN9v4qAo_2zNHKbMOFIFwW1Fm-pLmOso',
    appId: '1:442693512571:android:4c7a541b1b31baec2da1de',
    messagingSenderId: '442693512571',
    projectId: 'sportfields-ff16a',
    databaseURL: 'https://sportfields-ff16a-default-rtdb.firebaseio.com',
    storageBucket: 'sportfields-ff16a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmfGcsIOaBx0FRqPLTc9EfmC66Ynsdek',
    appId: '1:442693512571:ios:c124c8644a769f192da1de',
    messagingSenderId: '442693512571',
    projectId: 'sportfields-ff16a',
    databaseURL: 'https://sportfields-ff16a-default-rtdb.firebaseio.com',
    storageBucket: 'sportfields-ff16a.firebasestorage.app',
    iosBundleId: 'com.example.fieldshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmfGcsIOaBx0FRqPLTc9EfmC66Ynsdek',
    appId: '1:442693512571:ios:c124c8644a769f192da1de',
    messagingSenderId: '442693512571',
    projectId: 'sportfields-ff16a',
    databaseURL: 'https://sportfields-ff16a-default-rtdb.firebaseio.com',
    storageBucket: 'sportfields-ff16a.firebasestorage.app',
    iosBundleId: 'com.example.fieldshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf24iLI8u6sWdyJMNw-Q5_ueJo6Jl38fU',
    appId: '1:442693512571:web:be122482449356fc2da1de',
    messagingSenderId: '442693512571',
    projectId: 'sportfields-ff16a',
    authDomain: 'sportfields-ff16a.firebaseapp.com',
    databaseURL: 'https://sportfields-ff16a-default-rtdb.firebaseio.com',
    storageBucket: 'sportfields-ff16a.firebasestorage.app',
    measurementId: 'G-BM1M2DJMY2',
  );
}
